### PR TITLE
Update routes to support Settings-Environment Variables

### PR DESCRIPTION
**Pull request by lyalamanchili**
These endpoints are to support setting environment variables - https://docs.travis-ci.com/api#settings:-environment-variables

@pwmckenna Can you please merge the pull request?

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Seems legit

**Comment by ljharb** [comment]
@lyalamanchili altho tests are failing.

**Comment by pwmckenna** [comment]
lgtm. @ljharb you can merge/publish correct?

**Comment by ljharb** [comment]
Yup, I can! I'm going to let it sit in master for a bit before releasing, tho, and I'm hesitant to release before travis-ci can be fixed.

**Comment by travi** [comment]
i'm very confused by this addition but its quite likely that i'm missing something somewhat obvious. 

when i attempt to even try getting env vars, with 
```js
travis.settings.env_vars.get((err, res) => {
    if (err) console.log(err)
    else console.log(res)
  })
```

i get the following error: `Error: Couldn't find repository`

from [the docs](https://docs.travis-ci.com/api/?http#settings-environment-variables), it looks like the `repository_id` needs to be provided as a query parameter, but i haven't figured out how to provide query parameters. am i overlooking how to supply query parameters?

**Pull request merged**
